on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }} # required
          notify_when: 'failure'
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
          notify_when: 'failure'
          mention_users: 'U0160UUNH8S,U0080UUAA9N'
          mention_users_when: 'failure,warnings'
          mention_groups: 'SAZ94GDB8'
          mention_groups_when: 'failure,warnings'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}